-- SQL Schema for Blockage Survey Platform
-- Run this in your Supabase SQL Editor

-- 1. Create Respondents Table (Basic Info)
CREATE TABLE IF NOT EXISTS respondents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    full_name TEXT NOT NULL,
    employee_id TEXT UNIQUE NOT NULL,
    region TEXT, -- Free text field
    vertical TEXT, -- 'CH' or 'SFM'
    education_level TEXT,
    stream TEXT,
    course_name TEXT,
    year_of_passing TEXT,
    percentage_cgpa TEXT,
    certifications TEXT,
    current_designation TEXT,
    current_branch TEXT,
    department TEXT,
    experience_at_agarwal TEXT,
    total_experience TEXT,
    previous_roles TEXT,
    previous_designations TEXT,
    key_responsibilities TEXT,
    languages_known JSONB DEFAULT '[]'::jsonb,
    computer_skills JSONB DEFAULT '[]'::jsonb,
    total_score INTEGER DEFAULT 0,
    duration_seconds INTEGER DEFAULT 0,
    quality_flag TEXT DEFAULT 'Good'
);

-- 2. Create Responses Table (Individual Answers)
CREATE TABLE IF NOT EXISTS responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    respondent_id UUID REFERENCES respondents(id) ON DELETE CASCADE,
    question_number INTEGER NOT NULL,
    answer INTEGER NOT NULL, -- 1 for Yes, 0 for No
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Create Dimension Scores Table (Calculated Results)
CREATE TABLE IF NOT EXISTS dimension_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    respondent_id UUID REFERENCES respondents(id) ON DELETE CASCADE,
    dimension_name TEXT NOT NULL,
    score INTEGER NOT NULL, -- 0 to 10
    interpretation TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Create Global Settings Table
CREATE TABLE IF NOT EXISTS settings (
    id TEXT PRIMARY KEY DEFAULT 'global_settings',
    survey_title TEXT DEFAULT 'Organizational Blockage Survey',
    is_active BOOLEAN DEFAULT true,
    announcement_banner TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Insert initial settings
INSERT INTO settings (id, survey_title, is_active)
VALUES ('global_settings', 'Organizational Blockage Survey', true)
ON CONFLICT (id) DO NOTHING;

-- 6. CONFIGURE ROW LEVEL SECURITY (RLS)
-- Enable RLS on all tables
ALTER TABLE respondents ENABLE ROW LEVEL SECURITY;
ALTER TABLE responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE dimension_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- 7. CREATE POLICIES (Allow Public Submission + Stealth Admin Access)

-- Policies for Respondents
CREATE POLICY "Enable insert for all" ON respondents FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all" ON respondents FOR SELECT USING (true);

-- Policies for Responses
CREATE POLICY "Enable insert for all" ON responses FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all" ON responses FOR SELECT USING (true);

-- Policies for Dimension Scores
CREATE POLICY "Enable insert for all" ON dimension_scores FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read for all" ON dimension_scores FOR SELECT USING (true);

-- Policies for Settings
CREATE POLICY "Enable read for all" ON settings FOR SELECT USING (true);
CREATE POLICY "Enable update for all" ON settings FOR UPDATE USING (true);

-- 8. PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_responses_respondent ON responses(respondent_id);
CREATE INDEX IF NOT EXISTS idx_scores_respondent ON dimension_scores(respondent_id);
CREATE INDEX IF NOT EXISTS idx_respondents_emp_id ON respondents(employee_id);
